### ISSUE TITLE
스펙 & 기능 정리 TODO

### ISSUE THREAD

**Issue by alrud0x0** [alrud0x0/stock_game#1]
#### ~ 12/15
- [x] 필요 기능 정리
- [x] 화면 flow 정리
https://moqups.com/
- [x] CRUD API 작성
https://stoplight.io/
- [x] db schema 작성
https://dbdiagram.io
- [x] 아키텍처 구성
https://poiemaweb.com/nodejs-mysql

**Comment by alrud0x0** [comment]
### 사용자
POST /user
GET  /user/{userID}
GET  /users                  : 모든멤버
PUT  /user/{userID}
DELETE /user/{userID}

### 게임
POST /game/{YYYYMMDD}
GET  /game/{YYYYMMDD}
GET  /games                  : 모든게임(히스토리)
DELETE /game/{YYYYMMDD}

#### 게임참여
POST /game/{YYYYMMDD}/user/{userID}/stock/{stockID}
#### 게임수정
PUT  /game/{YYYYMMDD}/user/{userID}/stock/{stockID}

### 주식
주식 정보 가져오는 API?

**Comment by alrud0x0** [comment]
## DB Scheme 
### 사용자
- 사용자를 구분할 unique ID 필요

### 포인트
- 사용자 id ( 사용자 > 사용자별 Id)
- 게임 id (게임 > 게임별 id)
- 참여포인트 
- 순위권포인트

### 주식정보
- 주식을 구분할 unique ID (주식id로 하면될듯)
- 현재가격 : 매일 update -> 업데이트 주기 필요

### 게임(히스토리)
- 게임별 id : 회차로 구분
- 게임 start date
- 게임 end date

### 게임별 주식
- 게임별 Id(게임 > 게임별 Id)
- 투표한 사용자(사용자 > 사용자별 id)
- 주식 id (주식정보 > 주식id)
- 주식 명 (주식정보 > 주식명)
- 금요일 종가 (주식정보 > 현재가)
- 현재가 (주식정보 > 현재가)
- 현재가 대비 상승 퍼센트

**Comment by alrud0x0** [comment]
## 아키텍처?
- front : Vue
- server : GO lang?, nodejs?
- db : mysql ?
-

**Comment by mr-sense** [comment]
<img width="700" alt="스크린샷 2020-01-14 오전 10 18 08" src="https://user-images.githubusercontent.com/27203639/72305507-5ae39200-36b7-11ea-9607-7ba1af7db71b.png">

```
Table users as U {
  id int [pk, increment]
  passwd varchar
  name varchar
  point long
}

Table stocks as S {
  id int [pk, increment]
  name varchar
  price long
}

Table user_games as UG {
  user_id int [ref: > U.id] // inline relationship (many-to-one)
stock_id int [ref: > S.id] // inline relationship (many-to-one)
  game_id int [ref: > G.id] // inline relationship (many-to-one)
  why varchar
}

Table stock_games as SG {
  stock_id int [ref: > S.id] // inline relationship (many-to-one)
  game_id int [ref: > G.id] // inline relationship (many-to-one)
  last_price long
  current long
}

Table games as G {
  id int [pk, increment] // auto-increment
  start datetime
}
```

**Comment by mr-sense** [comment]
사용자
```
POST /users
{
  "name": "",
  "passwd": ""
}
GET /users/{userID}
GET /users : 모든멤버
PUT /users/{userID}
{
  "point": 0
}
DELETE /users/{userID}
```

주식
```
POST /stocks
{
  "stockID": "",
  "name": "",
  "price": 0
}
GET /stocks
PUT /stocks/{stockID}
{
  "price": 0
}
DELETE /stocks/{stockID}
```

게임
```
POST /games
{
  "start": "YYYYMMDD"
}
GET /games/{YYYYMMDD}
GET /games : 모든게임(히스토리)
DELETE /games/{YYYYMMDD}
```

게임참여
```
POST /games/{YYYYMMDD}/users/{userID}
{
  "stock": "",
  "why": ""
}
PUT /games/{YYYYMMDD}/users/{userID}
{
  "stock": "",
  "why": ""
}
GET /games/{YYYYMMDD}/users/
```

사용자 게임
```
GET /users/{userID}/games/
POST /users/{userID}/games/{YYYYMMDD}
[
  {
    "stockID": "",
    "why": ""
  },
  ...
]
{
  "stockID": "",
  "why": ""
}
GET /users/{userID}/games/{YYYYMMDD}
PUT /users/{userID}/games/{YYYYMMDD}
{
  "stockID": "",
  "why": ""
}
DELETE /users/{userID}/games/{YYYYMMDD}
DELETE /users/{userID}/games/{YYYYMMDD}/stocks/{stockID}
```

주식
주식 정보 가져오는 API?
