### ISSUE TITLE
Vue 프로토 타입 구현 TODO

### ISSUE THREAD

**Issue by alrud0x0** [alrud0x0/stock_game#2]
## TODO
- [x] 개발환경 구성 (vue-cli)   #8
- [ ] 프로젝트 구조(디렉토리) 구성 #9
  - [ ] 컴포넌트 구성 
- 프론트 demo
  - [x] 전체화면 껍데기 #10 
  - [x] HOME 화면 #11 
  - [x] 진행중 게임 화면 #17 
  - [ ] 게임 히스토리 화면
  - [x] ~upcoming 게임 화면~ => 불필요
  - [ ] 투표 참여 팝업 
  - [x] 각 주식별 투표 조회 팝업 #17 
    - 우선 테이블로 구현
  - [x] 랭킹 화면  #16 
  - [ ] 회원가입화면
  - [ ] 로그인화면

* 기능부터 개발하고 디자인은 나중에

**Comment by alrud0x0** [comment]
## 개발환경 구현
### Vue-Cli
* [홈페이지](https://cli.vuejs.org/)
#### Install
* [ref](https://cli.vuejs.org/guide/installation.html)
```console
$ npm install -g @vue/cli
(..)
$ vue --version
3.9.2
```
> npm: command not found 떨어지면 node 설치 해주면 된다. [홈페이지](https://nodejs.org/en/)
```
This package has installed:
	•	Node.js v10.16.0 to /usr/local/bin/node
	•	npm v6.9.0 to /usr/local/bin/npm
Make sure that /usr/local/bin is in your $PATH.
```
#### 프로젝트 생성
```console
$ vue create stockgame


Vue CLI v3.9.2
┌───────────────────────────┐
│  Update available: 4.1.2  │
└───────────────────────────┘
? Please pick a preset: default (babel, eslint)


Vue CLI v3.9.2
✨  Creating project in..../stockgame.
🗃  Initializing git repository...
⚙  Installing CLI plugins. This might take a while...


> fsevents@1.2.11 install 
..../stockgame/node_modules/fsevents
> node-gyp rebuild

  SOLINK_MODULE(target) Release/.node
  CXX(target) Release/obj.target/fse/fsevents.o
  SOLINK_MODULE(target) Release/fse.node

> yorkie@2.0.0 install ..../stockgame/node_modules/yorkie
> node bin/install.js

setting up Git hooks
done


> core-js@3.6.3 postinstall 
..../stockgame/node_modules/core-js
> node -e "try{require('./postinstall')}catch(e){}"


> ejs@2.7.4 postinstall ..../stockgame/node_modules/ejs
> node ./postinstall.js

added 1208 packages from 843 contributors and audited 24166 packages in 29.027s
found 0 vulnerabilities

🚀  Invoking generators...
📦  Installing additional dependencies...

added 59 packages from 53 contributors and audited 24453 packages in 7.866s
found 0 vulnerabilities



   ╭────────────────────────────────────────────────────────────────╮
   │                                                                │
   │       New minor version of npm available! 6.9.0 → 6.13.6       │
   │   Changelog: https://github.com/npm/cli/releases/tag/v6.13.6   │
   │               Run npm install -g npm to update!                │
   │                                                                │
   ╰────────────────────────────────────────────────────────────────╯

⚓  Running completion hooks...

📄  Generating README.md...

🎉  Successfully created project stockgame.
👉  Get started with the following commands:

 $ cd stockgame
 $ npm run serve
```

**Comment by alrud0x0** [comment]
## 프로젝트 구조 구성
```
$ ls -l
total 880
-rw-r--r--    1 user  staff     362 Jan 13 16:32 README.md
-rw-r--r--    1 user  staff      73 Jan 13 16:32 babel.config.js
drwxr-xr-x  823 user  staff   26336 Jan 13 16:32 node_modules
-rw-r--r--    1 user  staff  434344 Jan 13 16:32 package-lock.json
-rw-r--r--    1 user  staff     839 Jan 13 16:32 package.json
drwxr-xr-x    4 user  staff     128 Jan 13 16:32 public
drwxr-xr-x    6 user  staff     192 Jan 13 16:32 src
```

**Comment by alrud0x0** [comment]
## free icon
https://www.freepik.com/popular-icons

**Comment by alrud0x0** [comment]
## 참고 template
http://ndesaintheme.com/devin/#demos
